import type { StoreBanner, StoreBrand, StoreCategory, StoreProduct, StoreTestimonial } from "@/lib/store-types"

export const STORE_CATEGORIES: StoreCategory[] = [
  {
    slug: "televisions",
    name: "Televisions",
    nameSw: "Runinga",
    description: "Smart TVs, UHD displays, and living-room entertainment screens.",
    descriptionSw: "Smart TV, skrini za UHD na runinga za sebuleni.",
    icon: "Tv",
    featured: true,
  },
  {
    slug: "refrigerators",
    name: "Refrigerators",
    nameSw: "Friji",
    description: "Single-door, double-door, and premium cooling solutions.",
    descriptionSw: "Friji za mlango mmoja, miwili na suluhisho bora za kupooza.",
    icon: "Refrigerator",
    featured: true,
  },
  {
    slug: "freezers",
    name: "Freezers",
    nameSw: "Friza",
    description: "Chest freezers and upright freezers for home and business use.",
    descriptionSw: "Friza za juu na za kusimama kwa matumizi ya nyumbani na biashara.",
    icon: "Snowflake",
    featured: true,
  },
  {
    slug: "washing-machines",
    name: "Washing Machines",
    nameSw: "Mashine za kufulia",
    description: "Top-load and front-load washers designed for family use.",
    descriptionSw: "Mashine za kufulia za juu na mbele kwa matumizi ya familia.",
    icon: "Shirt",
    featured: true,
  },
  {
    slug: "cookers-ovens",
    name: "Cookers & Ovens",
    nameSw: "Cookers na Ovens",
    description: "Gas cookers, electric cookers, and built-in oven solutions.",
    descriptionSw: "Cookers za gesi, umeme na ovens zilizojengewa ndani.",
    icon: "ChefHat",
    featured: true,
  },
  {
    slug: "microwaves",
    name: "Microwaves",
    nameSw: "Microwave",
    description: "Compact and family-size microwaves for fast cooking.",
    descriptionSw: "Microwave ndogo na kubwa za kupika kwa haraka.",
    icon: "Microwave",
    featured: false,
  },
  {
    slug: "blenders-mixers",
    name: "Blenders & Mixers",
    nameSw: "Blender na Mixer",
    description: "Everyday blending, juicing, and kitchen prep appliances.",
    descriptionSw: "Vifaa vya kuchanganya, kutengeneza juisi na maandalizi ya jikoni.",
    icon: "Blend",
    featured: false,
  },
  {
    slug: "kettles",
    name: "Kettles",
    nameSw: "Birika za umeme",
    description: "Fast-boil electric kettles for home and office use.",
    descriptionSw: "Birika za umeme zenye kuchemsha haraka kwa nyumbani na ofisini.",
    icon: "Kettle",
    featured: false,
  },
  {
    slug: "irons",
    name: "Irons",
    nameSw: "Pasi",
    description: "Dry irons and steam irons for neat everyday care.",
    descriptionSw: "Pasi za kawaida na za mvuke kwa matumizi ya kila siku.",
    icon: "Shirt",
    featured: false,
  },
  {
    slug: "fans",
    name: "Fans",
    nameSw: "Feni",
    description: "Standing fans, wall fans, and ceiling fan cooling options.",
    descriptionSw: "Feni za kusimama, ukutani na dari kwa kupooza.",
    icon: "Fan",
    featured: true,
  },
  {
    slug: "speakers-audio",
    name: "Speakers & Audio",
    nameSw: "Spika na Audio",
    description: "Bluetooth speakers, soundbars, and home audio systems.",
    descriptionSw: "Spika za Bluetooth, soundbar na mifumo ya sauti ya nyumbani.",
    icon: "Speaker",
    featured: true,
  },
  {
    slug: "kitchen-appliances",
    name: "Kitchen Appliances",
    nameSw: "Vifaa vya jikoni",
    description: "Small appliances for food prep, warming, and convenience.",
    descriptionSw: "Vifaa vidogo vya jikoni kwa maandalizi ya chakula na urahisi.",
    icon: "Utensils",
    featured: false,
  },
  {
    slug: "home-essentials",
    name: "Home Essentials",
    nameSw: "Mahitaji ya nyumbani",
    description: "Helpful electrical essentials for everyday home living.",
    descriptionSw: "Mahitaji muhimu ya umeme kwa matumizi ya kila siku nyumbani.",
    icon: "House",
    featured: false,
  },
  {
    slug: "accessories",
    name: "Accessories",
    nameSw: "Vifaa vya ziada",
    description: "Mounts, cables, stands, and practical add-ons.",
    descriptionSw: "Mounts, nyaya, stendi na vifaa vya ziada vya matumizi.",
    icon: "Cable",
    featured: false,
  },
]

export const STORE_BRANDS: StoreBrand[] = [
  {
    slug: "samsung",
    name: "Samsung",
    description: "Known for premium TVs, refrigerators, and dependable smart-home appliances.",
    country: "South Korea",
    featured: true,
    logoLabel: "S",
  },
  {
    slug: "lg",
    name: "LG",
    description: "Energy-conscious appliances with smart controls and clean industrial design.",
    country: "South Korea",
    featured: true,
    logoLabel: "LG",
  },
  {
    slug: "hisense",
    name: "Hisense",
    description: "Popular value-for-money televisions, cooling, and kitchen appliances.",
    country: "China",
    featured: true,
    logoLabel: "H",
  },
  {
    slug: "haier",
    name: "Haier",
    description: "Reliable refrigeration and laundry appliances for busy households.",
    country: "China",
    featured: true,
    logoLabel: "HA",
  },
  {
    slug: "nikai",
    name: "Nikai",
    description: "Practical small appliances, kettles, irons, and microwave solutions.",
    country: "UAE",
    featured: false,
    logoLabel: "N",
  },
  {
    slug: "sony",
    name: "Sony",
    description: "Premium entertainment systems with excellent picture and sound performance.",
    country: "Japan",
    featured: true,
    logoLabel: "SO",
  },
]

export const HOME_BANNER: StoreBanner = {
  eyebrow: "Blue-and-gold appliance shopping for Tanzania",
  eyebrowSw: "Ununuzi wa vifaa vya rangi ya bluu na dhahabu Tanzania",
  title: "Upgrade your home with dependable appliances and direct WhatsApp ordering.",
  titleSw: "Boresha nyumba yako kwa vifaa vya kuaminika na uagizaji wa moja kwa moja kwa WhatsApp.",
  description:
    "Browse TVs, fridges, washing machines, cookers, speakers, and everyday kitchen essentials with clear specs, warranty details, and direct support from Albert Ochieng.",
  descriptionSw:
    "Nunua TV, friji, mashine za kufulia, cookers, spika na vifaa muhimu vya jikoni ukipata vipimo wazi, maelezo ya dhamana na msaada wa moja kwa moja kutoka kwa Albert Ochieng.",
  ctaLabel: "Shop appliances",
  ctaLabelSw: "Nunua vifaa",
  ctaHref: "/shop",
}

export const STORE_TESTIMONIALS: StoreTestimonial[] = [
  {
    name: "Neema M.",
    city: "Dar es Salaam",
    role: "Homeowner",
    roleSw: "Mmiliki wa nyumba",
    quote: "The fridge arrived in great condition and the team confirmed delivery timing on WhatsApp before dispatch.",
    quoteSw: "Friji ilifika ikiwa salama na timu ilinithibitishia muda wa kufikishwa kupitia WhatsApp kabla ya kutuma.",
    rating: 5,
  },
  {
    name: "Juma S.",
    city: "Mwanza",
    role: "Restaurant owner",
    roleSw: "Mmiliki wa mgahawa",
    quote: "I appreciated the clear freezer specs and warranty information. It made the buying decision much easier.",
    quoteSw: "Nilifurahia kuona vipimo vya friza na maelezo ya dhamana wazi. Ilinirahisishia sana kufanya uamuzi wa kununua.",
    rating: 5,
  },
  {
    name: "Amina R.",
    city: "Arusha",
    role: "Busy parent",
    roleSw: "Mzazi mwenye shughuli nyingi",
    quote: "The washing machine page explained installation and power details properly, which gave me confidence to order online.",
    quoteSw: "Ukurasa wa mashine ya kufulia ulieleza vizuri usakinishaji na matumizi ya umeme, jambo lililonipa uhakika wa kuagiza mtandaoni.",
    rating: 5,
  },
]

export const STORE_PRODUCTS: StoreProduct[] = [
  {
    slug: "samsung-crystal-uhd-55-smart-tv",
    name: "Samsung Crystal UHD 55\" Smart TV",
    nameSw: "Samsung Crystal UHD 55\" Smart TV",
    sku: "TV-SAM-55CU7000",
    brandSlug: "samsung",
    categorySlug: "televisions",
    subcategorySlug: "smart-tv",
    price: 1650000,
    discountPrice: 1495000,
    stock: 12,
    availability: "IN_STOCK",
    warrantyMonths: 24,
    modelNumber: "UA55CU7000",
    shortDescription: "A sharp 4K television for modern living rooms with streaming apps and vibrant HDR detail.",
    shortDescriptionSw: "Runinga kali ya 4K kwa sebule za kisasa yenye apps za streaming na HDR nzuri.",
    description:
      "This 55-inch Samsung smart TV balances premium picture quality with fast streaming access, multiple HDMI inputs, and a slim profile that suits family living rooms.",
    descriptionSw:
      "TV hii ya Samsung ya inchi 55 inatoa picha bora, streaming ya haraka, HDMI nyingi na muonekano mwembamba unaofaa sebule ya familia.",
    keyFeatures: ["55-inch 4K UHD panel", "Tizen smart platform", "HDR support", "3 HDMI ports"],
    keyFeaturesSw: ["Skrini ya 4K UHD ya inchi 55", "Mfumo wa Tizen", "Inaunga mkono HDR", "Port 3 za HDMI"],
    technicalSpecifications: [
      { group: "Display", label: "Resolution", value: "3840 x 2160" },
      { group: "Connectivity", label: "Wi-Fi", value: "Built-in" },
      { group: "Ports", label: "HDMI", value: "3" },
    ],
    energyDetails: "Eco mode with average household usage efficiency.",
    dimensions: "1230 x 707 x 60 mm",
    weightKg: 13.4,
    image: "/smart-led-tv.jpg",
    gallery: ["/smart-led-tv.jpg", "/placeholder.svg"],
    featured: true,
    trending: true,
    newArrival: false,
    rating: 4.8,
    reviewCount: 38,
    deliveryEligible: true,
    installationInfo: "Wall-mount installation support available on request in Dar es Salaam.",
  },
  {
    slug: "lg-420l-double-door-refrigerator",
    name: "LG 420L Double Door Refrigerator",
    nameSw: "LG 420L Friji ya milango miwili",
    sku: "RF-LG-420DD",
    brandSlug: "lg",
    categorySlug: "refrigerators",
    subcategorySlug: "double-door",
    price: 2390000,
    discountPrice: 2240000,
    stock: 6,
    availability: "LOW_STOCK",
    warrantyMonths: 24,
    modelNumber: "LG-GN-C422",
    shortDescription: "Spacious refrigerator with inverter efficiency and organized storage for medium to large households.",
    shortDescriptionSw: "Friji kubwa yenye inverter na nafasi nzuri ya kuhifadhi kwa familia za kati na kubwa.",
    description:
      "A practical family refrigerator with fresh-food capacity, low-noise operation, and dependable cooling performance for warm Tanzanian climates.",
    descriptionSw:
      "Friji ya familia yenye nafasi kubwa ya kuhifadhi chakula, kelele ndogo na utendaji mzuri wa kupooza kwa hali ya hewa ya Tanzania.",
    keyFeatures: ["420-liter capacity", "Smart inverter compressor", "Tempered glass shelves", "Low-noise cooling"],
    keyFeaturesSw: ["Uwezo wa lita 420", "Kompresa ya smart inverter", "Rafu za kioo imara", "Kupooza kwa kelele ndogo"],
    technicalSpecifications: [
      { group: "Cooling", label: "Compressor", value: "Inverter" },
      { group: "Storage", label: "Net volume", value: "420L" },
      { group: "Energy", label: "Consumption", value: "Low-power profile" },
    ],
    energyDetails: "Inverter technology designed to reduce energy draw during steady cooling cycles.",
    dimensions: "700 x 1780 x 680 mm",
    weightKg: 67,
    image: "/catalog/refrigerator.svg",
    gallery: ["/catalog/refrigerator.svg", "/catalog/refrigerator-open.svg"],
    featured: true,
    trending: true,
    newArrival: false,
    rating: 4.7,
    reviewCount: 21,
    deliveryEligible: true,
    installationInfo: "Requires upright transport and at least 4 hours rest before first power-on.",
  },
  {
    slug: "haier-300l-chest-freezer",
    name: "Haier 300L Chest Freezer",
    nameSw: "Haier 300L Friza ya kulaza",
    sku: "FZ-HA-300CH",
    brandSlug: "haier",
    categorySlug: "freezers",
    subcategorySlug: "chest-freezer",
    price: 1380000,
    stock: 10,
    availability: "IN_STOCK",
    warrantyMonths: 18,
    modelNumber: "HF-300C",
    shortDescription: "Reliable chest freezer built for households, shops, and food businesses.",
    shortDescriptionSw: "Friza ya kuaminika kwa nyumba, maduka na biashara za chakula.",
    description:
      "This Haier chest freezer offers generous cold storage, a strong lid seal, and dependable hold-over performance during short power interruptions.",
    descriptionSw:
      "Friza hii ya Haier ina nafasi nzuri ya kuhifadhi, kifuniko imara na uwezo wa kuhifadhi ubaridi hata umeme ukikatika kwa muda mfupi.",
    keyFeatures: ["300-liter storage", "Adjustable thermostat", "Power interruption retention", "Interior basket"],
    keyFeaturesSw: ["Uwezo wa lita 300", "Thermostat inayorekebishwa", "Hifadhi ya ubaridi umeme ukikatika", "Kikapu cha ndani"],
    technicalSpecifications: [
      { group: "Capacity", label: "Volume", value: "300L" },
      { group: "Build", label: "Type", value: "Chest freezer" },
      { group: "Cooling", label: "Control", value: "Manual thermostat" },
    ],
    energyDetails: "Efficient compressor tuned for all-day storage use.",
    dimensions: "1120 x 845 x 670 mm",
    weightKg: 42,
    image: "/catalog/freezer.svg",
    gallery: ["/catalog/freezer.svg", "/catalog/freezer-detail.svg"],
    featured: true,
    trending: false,
    newArrival: true,
    rating: 4.6,
    reviewCount: 14,
    deliveryEligible: true,
    installationInfo: "Best placed on a level surface with rear ventilation clearance.",
  },
  {
    slug: "hisense-9kg-front-load-washer",
    name: "Hisense 9KG Front Load Washing Machine",
    nameSw: "Hisense 9KG Mashine ya kufulia ya mbele",
    sku: "WM-HI-9FL",
    brandSlug: "hisense",
    categorySlug: "washing-machines",
    subcategorySlug: "front-load",
    price: 1850000,
    discountPrice: 1760000,
    stock: 5,
    availability: "LOW_STOCK",
    warrantyMonths: 24,
    modelNumber: "WFQY9014",
    shortDescription: "Family-size front-load washing machine with multiple wash programs and quiet operation.",
    shortDescriptionSw: "Mashine ya kufulia ya mbele yenye ukubwa wa familia na programu nyingi za kuosha.",
    description:
      "A modern front-load washer ideal for busy households, with fabric care options, child lock, and efficient water use.",
    descriptionSw:
      "Mashine ya kisasa ya kufulia ya mbele inayofaa nyumba zenye shughuli nyingi, ikiwa na programu za kutunza nguo, child lock na matumizi bora ya maji.",
    keyFeatures: ["9KG drum", "Quick wash mode", "Child lock", "Multiple care programs"],
    keyFeaturesSw: ["Drum ya 9KG", "Quick wash", "Child lock", "Programu nyingi za kutunza nguo"],
    technicalSpecifications: [
      { group: "Load", label: "Capacity", value: "9KG" },
      { group: "Programs", label: "Wash modes", value: "15" },
      { group: "Spin", label: "Max spin", value: "1400 rpm" },
    ],
    energyDetails: "Balanced water and power usage for medium-size laundry loads.",
    dimensions: "595 x 850 x 600 mm",
    weightKg: 63,
    image: "/catalog/washer.svg",
    gallery: ["/catalog/washer.svg", "/catalog/washer-panel.svg"],
    featured: true,
    trending: true,
    newArrival: true,
    rating: 4.7,
    reviewCount: 17,
    deliveryEligible: true,
    installationInfo: "Requires stable water inlet, floor drain, and level placement before first use.",
  },
  {
    slug: "nikai-4-burner-gas-cooker",
    name: "Nikai 4 Burner Gas Cooker with Oven",
    nameSw: "Nikai Cooker ya gesi burners 4 yenye oven",
    sku: "CK-NI-4BO",
    brandSlug: "nikai",
    categorySlug: "cookers-ovens",
    subcategorySlug: "gas-cookers",
    price: 990000,
    stock: 9,
    availability: "IN_STOCK",
    warrantyMonths: 12,
    modelNumber: "NKGC-640",
    shortDescription: "Practical freestanding gas cooker with oven for everyday family cooking.",
    shortDescriptionSw: "Cooker ya gesi ya kusimama yenye oven kwa matumizi ya kila siku ya familia.",
    description:
      "A dependable cooking unit with four burners, oven space, and easy-clean surfaces suited to home kitchens.",
    descriptionSw:
      "Kifaa cha kupikia chenye burners nne, oven na uso unaosafishwa kwa urahisi, kinachofaa jikoni ya nyumbani.",
    keyFeatures: ["4 gas burners", "Integrated oven", "Easy-clean finish", "Strong pan supports"],
    keyFeaturesSw: ["Burners 4 za gesi", "Oven iliyojengewa", "Uso rahisi kusafisha", "Vishikio imara vya vyombo"],
    technicalSpecifications: [
      { group: "Cooking", label: "Burners", value: "4" },
      { group: "Oven", label: "Type", value: "Gas oven" },
      { group: "Finish", label: "Body", value: "Powder-coated steel" },
    ],
    energyDetails: "Uses LPG gas supply with standard household efficiency.",
    dimensions: "600 x 850 x 600 mm",
    weightKg: 39,
    image: "/catalog/cooker.svg",
    gallery: ["/catalog/cooker.svg", "/catalog/cooker-detail.svg"],
    featured: true,
    trending: false,
    newArrival: false,
    rating: 4.5,
    reviewCount: 13,
    deliveryEligible: true,
    installationInfo: "Gas connection should be handled by a qualified technician.",
  },
  {
    slug: "nikai-25l-digital-microwave",
    name: "Nikai 25L Digital Microwave",
    nameSw: "Nikai Microwave ya dijitali 25L",
    sku: "MW-NI-25D",
    brandSlug: "nikai",
    categorySlug: "microwaves",
    subcategorySlug: "countertop-microwave",
    price: 320000,
    stock: 16,
    availability: "IN_STOCK",
    warrantyMonths: 12,
    modelNumber: "NMO-25D",
    shortDescription: "Compact microwave for reheating, quick meals, and efficient kitchen routines.",
    shortDescriptionSw: "Microwave ndogo kwa kupasha chakula, mlo wa haraka na matumizi rahisi jikoni.",
    description:
      "A practical digital microwave with preset modes, timer control, and enough space for everyday family reheating and quick cooking.",
    descriptionSw:
      "Microwave ya vitendo yenye presets, timer na nafasi ya kutosha kwa matumizi ya kawaida ya familia.",
    keyFeatures: ["25-liter interior", "Digital timer", "Preset menus", "Defrost mode"],
    keyFeaturesSw: ["Uwezo wa lita 25", "Timer ya dijitali", "Preset menus", "Defrost mode"],
    technicalSpecifications: [
      { group: "Capacity", label: "Volume", value: "25L" },
      { group: "Control", label: "Interface", value: "Digital" },
      { group: "Programs", label: "Presets", value: "Multiple" },
    ],
    energyDetails: "Standard countertop microwave power profile.",
    dimensions: "485 x 290 x 410 mm",
    weightKg: 12,
    image: "/catalog/microwave.svg",
    gallery: ["/catalog/microwave.svg", "/catalog/microwave-open.svg"],
    featured: false,
    trending: true,
    newArrival: true,
    rating: 4.4,
    reviewCount: 11,
    deliveryEligible: true,
  },
  {
    slug: "nikai-heavy-duty-blender",
    name: "Nikai Heavy Duty Blender",
    nameSw: "Nikai Blender ya nguvu",
    sku: "BL-NI-HD01",
    brandSlug: "nikai",
    categorySlug: "blenders-mixers",
    subcategorySlug: "blenders",
    price: 145000,
    stock: 24,
    availability: "IN_STOCK",
    warrantyMonths: 12,
    modelNumber: "NBL-1800",
    shortDescription: "Strong countertop blender for juices, sauces, and small-batch meal prep.",
    shortDescriptionSw: "Blender imara kwa juisi, mchuzi na maandalizi madogo ya chakula.",
    description:
      "A reliable kitchen blender with durable blades, pulse control, and a family-friendly jug size suited to daily use.",
    descriptionSw:
      "Blender ya kuaminika jikoni yenye visu imara, pulse control na jug inayofaa matumizi ya familia kila siku.",
    keyFeatures: ["Multi-speed control", "Pulse function", "Large jug", "Stainless blades"],
    keyFeaturesSw: ["Speeds nyingi", "Pulse function", "Jug kubwa", "Visu vya chuma"],
    technicalSpecifications: [
      { group: "Motor", label: "Power", value: "700W" },
      { group: "Jar", label: "Capacity", value: "1.5L" },
      { group: "Control", label: "Modes", value: "3 speed + pulse" },
    ],
    energyDetails: "700W motor tuned for short blending cycles.",
    dimensions: "220 x 410 x 210 mm",
    weightKg: 3.8,
    image: "/catalog/blender.svg",
    gallery: ["/catalog/blender.svg", "/catalog/blender-detail.svg"],
    featured: false,
    trending: false,
    newArrival: true,
    rating: 4.3,
    reviewCount: 9,
    deliveryEligible: true,
  },
  {
    slug: "nikai-1-7l-electric-kettle",
    name: "Nikai 1.7L Electric Kettle",
    nameSw: "Nikai Birika la umeme 1.7L",
    sku: "KT-NI-17EL",
    brandSlug: "nikai",
    categorySlug: "kettles",
    subcategorySlug: "electric-kettles",
    price: 68000,
    stock: 40,
    availability: "IN_STOCK",
    warrantyMonths: 12,
    modelNumber: "NKT-1701",
    shortDescription: "Fast-boil kettle for tea, coffee, and quick kitchen prep.",
    shortDescriptionSw: "Birika linalochemsha haraka kwa chai, kahawa na maandalizi ya haraka.",
    description:
      "A practical everyday electric kettle with automatic shut-off, water-level window, and cordless convenience.",
    descriptionSw:
      "Birika la umeme la matumizi ya kila siku lenye kuzima yenyewe, dirisha la kiwango cha maji na urahisi wa cordless.",
    keyFeatures: ["1.7-liter body", "Auto shut-off", "Cordless base", "Water-level window"],
    keyFeaturesSw: ["Mwili wa lita 1.7", "Kuzima yenyewe", "Base isiyo na waya", "Dirisha la kiwango cha maji"],
    technicalSpecifications: [
      { group: "Capacity", label: "Volume", value: "1.7L" },
      { group: "Safety", label: "Protection", value: "Auto shut-off" },
      { group: "Power", label: "Rating", value: "2200W" },
    ],
    energyDetails: "Fast heating profile with automatic cut-off.",
    dimensions: "220 x 250 x 170 mm",
    weightKg: 1.2,
    image: "/catalog/kettle.svg",
    gallery: ["/catalog/kettle.svg"],
    featured: false,
    trending: true,
    newArrival: false,
    rating: 4.5,
    reviewCount: 15,
    deliveryEligible: true,
  },
  {
    slug: "nikai-steam-iron-2400w",
    name: "Nikai Steam Iron 2400W",
    nameSw: "Nikai Pasi ya mvuke 2400W",
    sku: "IR-NI-ST24",
    brandSlug: "nikai",
    categorySlug: "irons",
    subcategorySlug: "steam-irons",
    price: 78000,
    stock: 28,
    availability: "IN_STOCK",
    warrantyMonths: 12,
    modelNumber: "NST-2400",
    shortDescription: "Smooth-glide steam iron for clean pressing and wrinkle control.",
    shortDescriptionSw: "Pasi ya mvuke yenye kuteleza vizuri kwa kupiga pasi safi na kuondoa mikunjo.",
    description:
      "An efficient home steam iron with ceramic soleplate, variable steam output, and a water tank sized for batch ironing.",
    descriptionSw:
      "Pasi ya mvuke ya nyumbani yenye ceramic soleplate, mvuke wa viwango mbalimbali na tanki la maji la matumizi ya kupiga pasi nyingi.",
    keyFeatures: ["2400W heating", "Ceramic soleplate", "Steam burst", "Anti-drip design"],
    keyFeaturesSw: ["Joto la 2400W", "Ceramic soleplate", "Steam burst", "Muundo wa anti-drip"],
    technicalSpecifications: [
      { group: "Power", label: "Rating", value: "2400W" },
      { group: "Plate", label: "Material", value: "Ceramic" },
      { group: "Steam", label: "Type", value: "Variable + burst" },
    ],
    energyDetails: "Designed for quick heating and short-duty household use.",
    dimensions: "300 x 150 x 130 mm",
    weightKg: 1.4,
    image: "/catalog/iron.svg",
    gallery: ["/catalog/iron.svg"],
    featured: false,
    trending: false,
    newArrival: true,
    rating: 4.2,
    reviewCount: 7,
    deliveryEligible: true,
  },
  {
    slug: "hisense-standing-fan-18-inch",
    name: "Hisense 18-inch Standing Fan",
    nameSw: "Hisense Feni ya kusimama inchi 18",
    sku: "FN-HI-18SF",
    brandSlug: "hisense",
    categorySlug: "fans",
    subcategorySlug: "standing-fans",
    price: 135000,
    discountPrice: 119000,
    stock: 18,
    availability: "IN_STOCK",
    warrantyMonths: 12,
    modelNumber: "HSF-18",
    shortDescription: "Quiet standing fan with broad oscillation and adjustable height for home comfort.",
    shortDescriptionSw: "Feni ya kusimama yenye kelele ndogo, mzunguko mpana na urefu unaorekebishwa.",
    description:
      "A dependable standing fan for bedrooms, offices, and living spaces, built for steady airflow in warm weather.",
    descriptionSw:
      "Feni ya kuaminika kwa vyumba, ofisi na sebule, iliyotengenezwa kwa upepo wa kudumu wakati wa joto.",
    keyFeatures: ["18-inch blades", "Height adjustable", "Oscillation", "3 speed settings"],
    keyFeaturesSw: ["Visu vya inchi 18", "Urefu unaorekebishwa", "Oscillation", "Speed 3"],
    technicalSpecifications: [
      { group: "Size", label: "Blade", value: "18 inch" },
      { group: "Control", label: "Speed levels", value: "3" },
      { group: "Movement", label: "Oscillation", value: "Yes" },
    ],
    energyDetails: "Low household power draw for all-day comfort use.",
    dimensions: "450 x 1250 x 430 mm",
    weightKg: 5.2,
    image: "/simple-ceiling-fan.png",
    gallery: ["/simple-ceiling-fan.png", "/catalog/fan.svg"],
    featured: true,
    trending: true,
    newArrival: false,
    rating: 4.4,
    reviewCount: 22,
    deliveryEligible: true,
  },
  {
    slug: "sony-soundbar-400w",
    name: "Sony Soundbar 400W",
    nameSw: "Sony Soundbar 400W",
    sku: "AU-SO-SB400",
    brandSlug: "sony",
    categorySlug: "speakers-audio",
    subcategorySlug: "soundbars",
    price: 680000,
    stock: 7,
    availability: "LOW_STOCK",
    warrantyMonths: 18,
    modelNumber: "HT-S400",
    shortDescription: "Compact soundbar system that upgrades TV audio with deeper bass and clear dialogue.",
    shortDescriptionSw: "Soundbar ndogo inayoboreshwa sauti ya TV kwa bass nzuri na maneno yaliyo wazi.",
    description:
      "A living-room friendly soundbar designed to pair easily with smart TVs for movies, sports, and daily entertainment.",
    descriptionSw:
      "Soundbar inayofaa sebule iliyotengenezwa kuunganishwa kwa urahisi na smart TV kwa sinema, michezo na burudani ya kila siku.",
    keyFeatures: ["400W output", "Wireless subwoofer", "Bluetooth audio", "TV pairing support"],
    keyFeaturesSw: ["Nguvu ya 400W", "Subwoofer isiyo na waya", "Bluetooth audio", "Inaunganishwa na TV"],
    technicalSpecifications: [
      { group: "Output", label: "Power", value: "400W" },
      { group: "Connectivity", label: "Bluetooth", value: "Yes" },
      { group: "System", label: "Subwoofer", value: "Wireless" },
    ],
    energyDetails: "Efficient standby and entertainment-room operating profile.",
    dimensions: "900 x 65 x 88 mm",
    weightKg: 7.8,
    image: "/bluetooth-speaker.jpg",
    gallery: ["/bluetooth-speaker.jpg", "/catalog/speaker.svg"],
    featured: true,
    trending: true,
    newArrival: false,
    rating: 4.6,
    reviewCount: 16,
    deliveryEligible: true,
  },
  {
    slug: "lg-43-inch-uhd-smart-tv",
    name: "LG 43-inch UHD Smart TV",
    nameSw: "LG Smart TV ya inchi 43 UHD",
    sku: "TV-LG-43UHD",
    brandSlug: "lg",
    categorySlug: "televisions",
    subcategorySlug: "smart-tv",
    price: 1080000,
    discountPrice: 995000,
    stock: 14,
    availability: "IN_STOCK",
    warrantyMonths: 24,
    modelNumber: "LG-43UQ75",
    shortDescription: "Compact 4K smart TV for bedrooms, apartments, and efficient family entertainment corners.",
    shortDescriptionSw: "Smart TV ya 4K ya ukubwa wa kati kwa chumba, apartment na sehemu za burudani nyumbani.",
    description:
      "A reliable 43-inch LG smart television with bright UHD clarity, app-ready streaming, and a footprint that fits smaller living spaces without sacrificing picture quality.",
    descriptionSw:
      "TV hii ya LG ya inchi 43 ina picha safi ya UHD, huduma za streaming, na ukubwa unaofaa nafasi ndogo bila kupunguza ubora wa picha.",
    keyFeatures: ["43-inch UHD panel", "Smart apps", "HDR support", "2 HDMI ports"],
    keyFeaturesSw: ["Skrini ya UHD ya inchi 43", "Apps za smart", "Inaunga mkono HDR", "Port 2 za HDMI"],
    technicalSpecifications: [
      { group: "Display", label: "Resolution", value: "3840 x 2160" },
      { group: "Connectivity", label: "Wi-Fi", value: "Built-in" },
      { group: "Ports", label: "HDMI", value: "2" },
    ],
    energyDetails: "Balanced power usage for apartment and bedroom viewing.",
    dimensions: "968 x 565 x 58 mm",
    weightKg: 8.9,
    image: "/catalog/tv-43.svg",
    gallery: ["/catalog/tv-43.svg", "/smart-led-tv.jpg"],
    featured: false,
    trending: true,
    newArrival: true,
    rating: 4.5,
    reviewCount: 12,
    deliveryEligible: true,
    installationInfo: "Wall-mount support available on request.",
  },
  {
    slug: "samsung-12kg-top-load-washer",
    name: "Samsung 12KG Top Load Washing Machine",
    nameSw: "Samsung Mashine ya kufulia ya juu 12KG",
    sku: "WM-SAM-12TL",
    brandSlug: "samsung",
    categorySlug: "washing-machines",
    subcategorySlug: "top-load",
    price: 1620000,
    stock: 8,
    availability: "IN_STOCK",
    warrantyMonths: 24,
    modelNumber: "WA12CG",
    shortDescription: "Large-capacity top-load washer for busy homes, rentals, and family laundry days.",
    shortDescriptionSw: "Mashine ya kufulia ya juu yenye ukubwa mkubwa kwa nyumba zenye shughuli nyingi na matumizi ya familia.",
    description:
      "A practical Samsung top-load washer with a generous drum, quick wash routines, and easy top access suited to larger households.",
    descriptionSw:
      "Mashine hii ya Samsung ya kufulia ya juu ina drum kubwa, programu za kuosha haraka, na matumizi rahisi kwa familia kubwa.",
    keyFeatures: ["12KG capacity", "Quick wash cycles", "Soft-close lid", "Child safety"],
    keyFeaturesSw: ["Uwezo wa 12KG", "Programu za haraka", "Kifuniko cha soft-close", "Usalama wa watoto"],
    technicalSpecifications: [
      { group: "Load", label: "Capacity", value: "12KG" },
      { group: "Control", label: "Programs", value: "Multiple preset cycles" },
      { group: "Design", label: "Type", value: "Top load" },
    ],
    energyDetails: "Designed for efficient family laundry loads.",
    dimensions: "610 x 1050 x 675 mm",
    weightKg: 45,
    image: "/catalog/top-load-washer.svg",
    gallery: ["/catalog/top-load-washer.svg", "/catalog/washer.svg"],
    featured: true,
    trending: false,
    newArrival: true,
    rating: 4.6,
    reviewCount: 10,
    deliveryEligible: true,
    installationInfo: "Requires stable water inlet and level surface.",
  },
  {
    slug: "hisense-mini-fridge-90l",
    name: "Hisense Mini Fridge 90L",
    nameSw: "Hisense Mini Friji 90L",
    sku: "RF-HI-90MINI",
    brandSlug: "hisense",
    categorySlug: "refrigerators",
    subcategorySlug: "single-door",
    price: 420000,
    stock: 19,
    availability: "IN_STOCK",
    warrantyMonths: 12,
    modelNumber: "H90S",
    shortDescription: "Compact fridge for offices, bedrooms, student spaces, and small apartments.",
    shortDescriptionSw: "Friji ndogo kwa ofisi, vyumba, hosteli, na apartment ndogo.",
    description:
      "A space-saving cooling option with practical shelf layout, low-noise performance, and simple temperature control for daily essentials.",
    descriptionSw:
      "Friji ya kuokoa nafasi yenye mpangilio mzuri wa rafu, kelele ndogo, na udhibiti rahisi wa joto kwa matumizi ya kila siku.",
    keyFeatures: ["90-liter storage", "Low-noise cooling", "Compact footprint", "Adjustable shelves"],
    keyFeaturesSw: ["Uwezo wa lita 90", "Kelele ndogo", "Ukubwa mdogo", "Rafu zinazorekebishwa"],
    technicalSpecifications: [
      { group: "Storage", label: "Net volume", value: "90L" },
      { group: "Design", label: "Door type", value: "Single door" },
      { group: "Control", label: "Temperature", value: "Manual dial" },
    ],
    energyDetails: "Low everyday power draw for small-space cooling.",
    dimensions: "480 x 830 x 500 mm",
    weightKg: 21,
    image: "/catalog/mini-fridge.svg",
    gallery: ["/catalog/mini-fridge.svg", "/catalog/refrigerator.svg"],
    featured: false,
    trending: true,
    newArrival: true,
    rating: 4.4,
    reviewCount: 8,
    deliveryEligible: true,
  },
  {
    slug: "nikai-microwave-grill-30l",
    name: "Nikai Microwave Grill 30L",
    nameSw: "Nikai Microwave Grill 30L",
    sku: "MW-NI-30GR",
    brandSlug: "nikai",
    categorySlug: "microwaves",
    subcategorySlug: "grill-microwave",
    price: 455000,
    stock: 11,
    availability: "IN_STOCK",
    warrantyMonths: 12,
    modelNumber: "NMG-30",
    shortDescription: "Microwave and grill combination for reheating, browning, and faster meal prep.",
    shortDescriptionSw: "Mchanganyiko wa microwave na grill kwa kupasha, kuoka juu, na maandalizi ya haraka ya chakula.",
    description:
      "A more versatile microwave option with grill functionality, multiple presets, and larger family-friendly capacity for kitchen convenience.",
    descriptionSw:
      "Microwave yenye uwezo zaidi kwa sababu ya grill, presets nyingi, na nafasi kubwa inayofaa matumizi ya familia jikoni.",
    keyFeatures: ["30-liter capacity", "Grill function", "Preset cooking", "Digital timer"],
    keyFeaturesSw: ["Uwezo wa lita 30", "Kazi ya grill", "Preset cooking", "Timer ya dijitali"],
    technicalSpecifications: [
      { group: "Capacity", label: "Volume", value: "30L" },
      { group: "Cooking", label: "Modes", value: "Microwave + grill" },
      { group: "Control", label: "Display", value: "Digital" },
    ],
    energyDetails: "Kitchen-friendly power profile for reheating and quick grilling.",
    dimensions: "520 x 330 x 430 mm",
    weightKg: 14.5,
    image: "/catalog/microwave-grill.svg",
    gallery: ["/catalog/microwave-grill.svg", "/catalog/microwave-open.svg"],
    featured: false,
    trending: true,
    newArrival: true,
    rating: 4.5,
    reviewCount: 9,
    deliveryEligible: true,
  },
]
